# DataSource Config
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: yours
    port: 587
    protocol: smtp
    properties:
      "mail.smtp.connectiontimeout": 60000
      "mail.smtp.timeout": 60000
      "mail.smtp.writetimeout": 60000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
    username: yours
  application:
    name: findFriend-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: 123456
#    NRRH3prTcs7es2An
  #redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  session:
    timeout: 2h

mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: isdelete # 全局逻辑删除字段名
        logic-delete-value: 1 # 逻辑已删除值
        logic-not-delete-value: 0 # 逻辑未删除值


server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dying.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
